name: camdn

services:
  camdn-api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/camdn:/usr/camdn
    env_file: "./api/.env"
    restart: unless-stopped
  camdn-client:
    build: ./client
    depends_on:
      camdn-api:
        condition: service_started
        restart: true
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/usr/camdn/src
  camdn-db:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_USER: camdn
      POSTGRES_PASSWORD: camdnTest
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/data/postgres
    restart: unless-stopped
  camdn-proxy:
    build: ./proxy
    depends_on:
      camdn-api:
        condition: service_started
        restart: true
      camdn-client:
        condition: service_started
        restart: true
    restart: unless-stopped
    ports:
      - "8080:80"
