name: camdn

services:
  camdn-api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/camdn:/usr/camdn
    env_file: "./api/.env"
    restart: unless-stopped
  camdn-client:
    build: ./client
    depends_on:
      camdn-api:
        condition: service_started
        restart: true
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/usr/camdn/src
  camdn-proxy:
    build: ./proxy
    depends_on:
      camdn-api:
        condition: service_started
        restart: true
      camdn-client:
        condition: service_started
        restart: true
    restart: unless-stopped
    ports:
      - "8080:80"
